# Generated by Django 4.2 on 2025-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa_travel', '0002_rename_description_accommodation_accommodation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_image',
            field=models.ImageField(blank=True, upload_to='accommodation'),
        ),
        migrations.AddField(
            model_name='activityandtour',
            name='at_image',
            field=models.ImageField(blank=True, upload_to='activity'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_image',
            field=models.ImageField(blank=True, upload_to='attraction'),
        ),
        migrations.AddField(
            model_name='foodandrestaurant',
            name='fd_image',
            field=models.ImageField(blank=True, upload_to='foodRestaurant'),
        ),
    ]
