# Generated by Django 4.2 on 2025-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa_travel', '0006_alter_client_client_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
