# Generated by Django 4.2 on 2025-04-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa_travel', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandtour',
            name='at_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandtour',
            name='at_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityandtour',
            name='at_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodandrestaurant',
            name='fd_map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodandrestaurant',
            name='fd_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodandrestaurant',
            name='fd_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
