# Generated by Django 4.2 on 2025-04-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa_travel', '0011_accommodation_accommodation_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='accommodation_map_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityandtour',
            name='at_map_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='attraction_map_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodandrestaurant',
            name='fd_map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
