# Generated by Django 4.2 on 2025-04-10 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa_travel', '0012_alter_accommodation_accommodation_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asa_travel.destination'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
